/*
================================================================================
十二路灰度采样与误差计算实现模块
================================================================================
【功能简介】
本文件同步读取 P1~P12 数字灰度输入，以从左到右的权重计算黑线位置误差，
并输出有效位掩码、有效数量、横线标志和丢线标志。

================================================================================
【函数定义】
- LineSensor_IsHigh：读取指定 GPIO 当前是否为高电平。
- LineSensor_Init：标记 SysConfig 已配置的灰度输入可用。
- LineSensor_IsInitialized：返回灰度模块初始化状态。
- LineSensor_Read：读取 12 路输入并计算加权质心、横线和丢线结果。

================================================================================
【使用说明】
1. 默认高电平表示检测到黑线，所有 12 个通道都参与计算。
2. 权重表和横线有效通道阈值已集中到 user_config.h。
3. sample 不得为 NULL；丢线时 error 清零，由上层根据历史误差恢复方向。
================================================================================
*/
#include "line_sensor.h"

#include "user_config.h"
#include "ti_msp_dl_config.h"

#include <stddef.h>

static bool g_initialized;

static uint8_t LineSensor_IsHigh(GPIO_Regs *port, uint32_t pin)
{
    return ((DL_GPIO_readPins(port, pin) & pin) != 0U) ? 1U : 0U;
}

bool LineSensor_Init(void)
{
    /* Pin mux and input mode are generated by SysConfig. */
    g_initialized = true;
    return true;
}

bool LineSensor_IsInitialized(void)
{
    return g_initialized;
}

void LineSensor_Read(LineSensorSample *sample)
{
    /*
     * r2 maps P1..P12 to -4.0..+4.0. PB23 remains P8, so all 12 channels
     * participate in the weighted centroid. Gray outputs are active high on
     * black according to the resource-board reference implementation.
     */
    static const int8_t weights_x10[12] = APP_LINE_SENSOR_WEIGHTS_X10;
    uint8_t active[12];
    uint8_t i;
    int32_t weighted_sum = 0;

    if (sample == NULL) {
        return;
    }

    active[0] = LineSensor_IsHigh(LINE_SENSORS_P1_PORT,
                                  LINE_SENSORS_P1_PIN);
    active[1] = LineSensor_IsHigh(LINE_SENSORS_P2_PORT,
                                  LINE_SENSORS_P2_PIN);
    active[2] = LineSensor_IsHigh(LINE_SENSORS_P3_PORT,
                                  LINE_SENSORS_P3_PIN);
    active[3] = LineSensor_IsHigh(LINE_SENSORS_P4_PORT,
                                  LINE_SENSORS_P4_PIN);
    active[4] = LineSensor_IsHigh(LINE_SENSORS_P5_PORT,
                                  LINE_SENSORS_P5_PIN);
    active[5] = LineSensor_IsHigh(LINE_SENSORS_P6_PORT,
                                  LINE_SENSORS_P6_PIN);
    active[6] = LineSensor_IsHigh(LINE_SENSORS_P7_PORT,
                                  LINE_SENSORS_P7_PIN);
    active[7] = LineSensor_IsHigh(LINE_SENSORS_P8_PORT,
                                  LINE_SENSORS_P8_PIN);
    active[8] = LineSensor_IsHigh(LINE_SENSORS_P9_PORT,
                                  LINE_SENSORS_P9_PIN);
    active[9] = LineSensor_IsHigh(LINE_SENSORS_P10_PORT,
                                  LINE_SENSORS_P10_PIN);
    active[10] = LineSensor_IsHigh(LINE_SENSORS_P11_PORT,
                                  LINE_SENSORS_P11_PIN);
    active[11] = LineSensor_IsHigh(LINE_SENSORS_P12_PORT,
                                   LINE_SENSORS_P12_PIN);

    sample->active_mask = 0U;
    sample->active_count = 0U;
    for (i = 0U; i < 12U; ++i) {
        if (active[i] != 0U) {
            sample->active_mask |= (uint16_t)(1UL << i);
            ++sample->active_count;
            weighted_sum += weights_x10[i];
        }
    }

    sample->lost = (sample->active_count == 0U) ? 1U : 0U;
    /* 默认阈值 8 对应 ceil(12 * 5/8)，保持 r2 的横线判定比例。 */
    sample->marker =
        (sample->active_count >= APP_LINE_SENSOR_MARKER_MIN_ACTIVE) ? 1U : 0U;
    if (sample->lost != 0U) {
        sample->error = 0.0f;
    } else {
        sample->error = ((float)weighted_sum) /
                        (10.0f * (float)sample->active_count);
    }
}
